const mongoose = require('mongoose');

const plantDataSchema = new mongoose.Schema({
    temperature: Number,
    humidity: Number,
    light: Number,
    air_quality: Number,
    ai_enabled: Number,
    ai_prediction: Number,
    ai_confidence: Number,
    health_score: Number,
    growth_status: Number,
    plant_advice: String,
    temp_eval: String,
    humi_eval: String,
    light_eval: String,
    air_eval: String,
    control_mode: String,
    relay1: Number,
    relay2: Number,
    relay3: Number,
    relay4: Number,
    relay1_status: String,
    relay2_status: String,
    relay3_status: String,
    relay4_status: String,
    trend_direction: Number,
    trend_strength: Number,
    trend_description: String,
    estimated_days_to_issue: Number,
    growth_rate: Number,
    predicted_yield: Number,
    resource_efficiency: Number,
    optimal_hours_count: Number,
    productivity_score: Number,
    daily_avg_health: Number,
    has_alert: Boolean,
    alert_level: String,
    alert_message: String,
    system_time: String,
    createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('PlantData', plantDataSchema);
